In [153]:
import requests
import csv
import pandas as pd
from pandas import DataFrame as df
import re

import os
from pandas.io.json import json_normalize
import urllib.request as request
import json

import operator
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

In [154]:
hiv_data1 = pd.read_excel("HIV_data1.xlsx")
hiv_data2 = pd.read_excel("HIV_data2.xlsx")
hiv_data3 = pd.read_excel("HIV_data3.xlsx")

## Data Cleaning for Sheet1

In [155]:
# Removing brackets and Numbers inside it
hiv_data1['Number of deaths due to HIV/AIDS'] = hiv_data1['Number of deaths due to HIV/AIDS'].str.replace(r"\[.*\]","")
hiv_data1['Number of deaths due to HIV/AIDS'] = hiv_data1['Number of deaths due to HIV/AIDS'].str.replace(r"\&.*\;","")

# remove spaces between the numbers
hiv_data1['Number of deaths due to HIV/AIDS'] = hiv_data1['Number of deaths due to HIV/AIDS'].str.replace(" ","")

# Convert the the column values from string to int
hiv_data1["Number of deaths due to HIV/AIDS"] = pd.to_numeric(hiv_data1["Number of deaths due to HIV/AIDS"])
hiv_data1.rename(columns = {'WHO region':'WHO_region'
                           }, inplace = True)
hiv_data1

          WHO_region  Year  Number of deaths due to HIV/AIDS
0             Global  2019                            690000
1             Global  2018                            730000
2             Global  2017                            760000
3             Global  2016                            800000
4             Global  2015                            830000
..               ...   ...                               ...
205  Western Pacific  1994                              7700
206  Western Pacific  1993                              5500
207  Western Pacific  1992                              4000
208  Western Pacific  1991                              2900
209  Western Pacific  1990                              2100

[210 rows x 3 columns]

In [156]:
hiv_data2.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Number of new HIV infections',
       'New HIV infections (per 1000 uninfected population)',
       'New HIV infections (per 1000 uninfected population).1',
       'New HIV infections (per 1000 uninfected population).2'],
      dtype='object')

In [157]:
hiv_data2 = hiv_data2.drop(hiv_data2.head(1).index)

In [158]:
hiv_data2.rename(columns = {'Unnamed: 0':'WHO_region', 'Unnamed: 1':'Year', 
                            'New HIV infections (per 1000 uninfected population)':'New HIV infections (per 1000 uninfected population)Both Sexes',
                            'New HIV infections (per 1000 uninfected population).1':'New HIV infections (per 1000 uninfected population)Male',
                            'New HIV infections (per 1000 uninfected population).2':'New HIV infections (per 1000 uninfected population)Female'
                           }, inplace = True) 
hiv_data2

,WHO_region,Year,Number of new HIV infections,New HIV infections (per 1000 uninfected population)Both Sexes,New HIV infections (per 1000 uninfected population)Male,New HIV infections (per 1000 uninfected population)Female
1,Global,2019,1 700 000 [1 200 000–2 200 000],0.22 [0.16–0.3],0.23 [0.17–0.32],0.21 [0.16-0.29]
2,Global,2018,1 700 000 [1 200 000–2 300 000],0.23 [0.17–0.31],0.24 [0.17–0.33],0.22 [0.16-0.3]
3,Global,2017,1 800 000 [1 300 000–2 400 000],0.24 [0.18–0.32],0.24 [0.18–0.34],0.23 [0.17-0.32]
4,Global,2016,1 800 000 [1 300 000–2 400 000],0.25 [0.18–0.34],0.25 [0.18–0.35],0.24 [0.18-0.33]
5,Global,2015,1 900 000 [1 400 000–2 500 000],0.26 [0.19–0.35],0.26 [0.19–0.36],0.26 [0.19-0.35]
...,...,...,...,...,...,...
206,Western Pacific,1994,140 000 [87 000–180 000],0.09 [0.05–0.12],0.13 [0.08–0.17],0.05 [0.03-0.06]
207,Western Pacific,1993,50 000 [32 000–67 000],0.03 [0.02–0.04],0.05 [0.03–0.06],0.02 [&lt;0.01-0.02]
208,Western Pacific,1992,40 000 [25 000–53 000],0.03 [0.02–0.03],0.04 [0.02–0.05],0.01 [&lt;0.01-0.02]
209,Western Pacific,1991,30 000 [19 000–40 000],0.02 [0.01–0.03],0.03 [0.02–0.04],&lt;0.01 [&lt;0.01-0.01]
210,Western Pacific,1990,23 000 [14 000–31 000],0.02 [&lt;0.01–0.02],0.02 [0.02–0.03],&lt;0.01 [&lt;0.01-&lt;0.01]

## Data cleaning for Sheet2

In [159]:
# Removing brackets and Numbers inside it
hiv_data2['Number of new HIV infections'] = hiv_data2['Number of new HIV infections'].str.replace(r"\[.*\]","")
hiv_data2['New HIV infections (per 1000 uninfected population)Both Sexes'] = hiv_data2['New HIV infections (per 1000 uninfected population)Both Sexes'].str.replace(r"\[.*\]","")
hiv_data2['New HIV infections (per 1000 uninfected population)Male'] = hiv_data2['New HIV infections (per 1000 uninfected population)Male'].str.replace(r"\[.*\]","")
hiv_data2['New HIV infections (per 1000 uninfected population)Female'] = hiv_data2['New HIV infections (per 1000 uninfected population)Female'].str.replace(r"\[.*\]","")

# Remove redundant information before values
hiv_data2['New HIV infections (per 1000 uninfected population)Female'] = hiv_data2['New HIV infections (per 1000 uninfected population)Female'].str.replace(r"\&.*\;","")
hiv_data2['New HIV infections (per 1000 uninfected population)Both Sexes'] = hiv_data2['New HIV infections (per 1000 uninfected population)Both Sexes'].str.replace(r"\&.*\;","")

# remove spaces between the numbers
hiv_data2['Number of new HIV infections'] = hiv_data2['Number of new HIV infections'].str.replace(" ","")
hiv_data2['New HIV infections (per 1000 uninfected population)Both Sexes'] = hiv_data2['New HIV infections (per 1000 uninfected population)Both Sexes'].str.replace(" ","")
hiv_data2['New HIV infections (per 1000 uninfected population)Male'] = hiv_data2['New HIV infections (per 1000 uninfected population)Male'].str.replace(" ","")
hiv_data2['New HIV infections (per 1000 uninfected population)Female'] = hiv_data2['New HIV infections (per 1000 uninfected population)Female'].str.replace(" ","")

# Convert the the column values from string to int
hiv_data2["Number of new HIV infections"] = pd.to_numeric(hiv_data2["Number of new HIV infections"])
hiv_data2["New HIV infections (per 1000 uninfected population)Both Sexes"] = pd.to_numeric(hiv_data2["New HIV infections (per 1000 uninfected population)Both Sexes"])
hiv_data2["New HIV infections (per 1000 uninfected population)Male"] = pd.to_numeric(hiv_data2["New HIV infections (per 1000 uninfected population)Male"])
hiv_data2["New HIV infections (per 1000 uninfected population)Female"] = pd.to_numeric(hiv_data2["New HIV infections (per 1000 uninfected population)Female"])

hiv_data2

,WHO_region,Year,Number of new HIV infections,New HIV infections (per 1000 uninfected population)Both Sexes,New HIV infections (per 1000 uninfected population)Male,New HIV infections (per 1000 uninfected population)Female
1,Global,2019,1700000,0.22,0.23,0.21
2,Global,2018,1700000,0.23,0.24,0.22
3,Global,2017,1800000,0.24,0.24,0.23
4,Global,2016,1800000,0.25,0.25,0.24
5,Global,2015,1900000,0.26,0.26,0.26
...,...,...,...,...,...,...
206,Western Pacific,1994,140000,0.09,0.13,0.05
207,Western Pacific,1993,50000,0.03,0.05,0.02
208,Western Pacific,1992,40000,0.03,0.04,0.01
209,Western Pacific,1991,30000,0.02,0.03,0.01
210,Western Pacific,1990,23000,0.02,0.02,0.01

## Data Cleaning for Datasheet 3

In [160]:
# remove spaces between the numbers
hiv_data3['PEOPLE HAVING HIV'] = hiv_data3['PEOPLE HAVING HIV'].str.replace(" ","")

# Convert the the column values from string to int
hiv_data3["PEOPLE HAVING HIV"] = pd.to_numeric(hiv_data3["PEOPLE HAVING HIV"])
hiv_data3.rename(columns = {'REGION':'WHO_region', 'YEAR':'Year', 
                            'PEOPLE HAVING HIV':'people having HIV'
                           }, inplace = True)
hiv_data3

          WHO_region  Year  people having HIV
0             Global  2019           38000000
1             Global  2018           37300000
2             Global  2017           36500000
3             Global  2016           35700000
4             Global  2015           34900000
..               ...   ...                ...
205  Western Pacific  1994             320000
206  Western Pacific  1993             200000
207  Western Pacific  1992             150000
208  Western Pacific  1991             120000
209  Western Pacific  1990              90000

[210 rows x 3 columns]

In [161]:
hiv_data1.to_csv("HIV1_cleaned_data.csv")
hiv_data2.to_csv("HIV2_cleaned_data.csv")
hiv_data3.to_csv("HIV3_cleaned_data.csv")